# Generated by Django 5.0.6 on 2024-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Financial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ISIN", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("asset_class", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("market_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
