# Generated by Django 5.0.6 on 2024-05-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanai_register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial", name="ISIN", field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="financial",
            name="asset_class",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="financial", name="cost_price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="financial", name="date", field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="financial", name="market_price", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="financial",
            name="symbol",
            field=models.CharField(max_length=150),
        ),
    ]
