# Generated by Django 5.0.6 on 2024-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ethanai_register",
            "0002_alter_financial_isin_alter_financial_asset_class_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="financial",
            name="date",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
