version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_NAME: EthanAiDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: EthanAiDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
